/* tslint:disable */
/* eslint-disable */
/*
Zapier AI Actions API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ConfigurationApi - axios parameter creator
 * @export
 */
export const ConfigurationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Provides a link to configure more actions. Alternatively, searching through apps and actions will provide more specific configuration links.
         * @summary Get Configuration Link
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConfigurationLink: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/configuration-link`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AccessPointApiKeyHeader required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "X-API-Key", keyParamName: "accessPointApiKeyHeader", configuration })
            // authentication AccessPointApiKeyQuery required
            await setApiKeyToObject({object: localVarQueryParameter, key: "api_key", keyParamName: "accessPointApiKeyQuery", configuration})
            // authentication AccessPointOAuth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "AccessPointOAuth", [], configuration)
            // authentication SessionAuth required
            await setApiKeyToObject({object: localVarHeaderParameter, type: "Cookie", key: "Cookie", keyParamName: "nlasession", configuration})

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/v1/configuration-link',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ConfigurationApi - functional programming interface
 * @export
 */
export const ConfigurationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ConfigurationApiAxiosParamCreator(configuration)
    return {
        /**
         * Provides a link to configure more actions. Alternatively, searching through apps and actions will provide more specific configuration links.
         * @summary Get Configuration Link
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getConfigurationLink(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getConfigurationLink(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ConfigurationApi - factory interface
 * @export
 */
export const ConfigurationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ConfigurationApiFp(configuration)
    return {
        /**
         * Provides a link to configure more actions. Alternatively, searching through apps and actions will provide more specific configuration links.
         * @summary Get Configuration Link
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConfigurationLink(options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getConfigurationLink(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ConfigurationApiGenerated - object-oriented interface
 * @export
 * @class ConfigurationApiGenerated
 * @extends {BaseAPI}
 */
export class ConfigurationApiGenerated extends BaseAPI {
    /**
     * Provides a link to configure more actions. Alternatively, searching through apps and actions will provide more specific configuration links.
     * @summary Get Configuration Link
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConfigurationApiGenerated
     */
    public getConfigurationLink(options?: AxiosRequestConfig) {
        return ConfigurationApiFp(this.configuration).getConfigurationLink(options).then((request) => request(this.axios, this.basePath));
    }
}
