/*
Zapier AI Actions API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * This is a summary of the results given the action that was executed.
 * @export
 * @interface ExecuteResponse
 */
export interface ExecuteResponse {
    /**
     * The id of the execution log.
     * @type {string}
     * @memberof ExecuteResponse
     */
    'id': string;
    /**
     * The name of the action that was executed.
     * @type {string}
     * @memberof ExecuteResponse
     */
    'action_used': string;
    /**
     * The params we used / will use to execute the action.
     * @type {object}
     * @memberof ExecuteResponse
     */
    'input_params': object;
    /**
     * The URL to run the action or review the AI choices the AI made for input_params given instructions.
     * @type {string}
     * @memberof ExecuteResponse
     */
    'review_url': string;
    /**
     * A trimmed down result of the first item of the full results. Ideal for humans and language models!
     * @type {object}
     * @memberof ExecuteResponse
     */
    'result'?: object;
    /**
     * The rest of the full results. Always returns an array of objects
     * @type {Array<object>}
     * @memberof ExecuteResponse
     */
    'additional_results': Array<object>;
    /**
     * Human readable labels for some of the keys in the result.
     * @type {object}
     * @memberof ExecuteResponse
     */
    'result_field_labels'?: object;
    /**
     * The status of the execution.
     * @type {string}
     * @memberof ExecuteResponse
     */
    'status'?: ExecuteResponseStatusEnum;
    /**
     * The error message if the execution failed.
     * @type {string}
     * @memberof ExecuteResponse
     */
    'error'?: string;
    /**
     * A hint for the assistant on what to do next.
     * @type {string}
     * @memberof ExecuteResponse
     */
    'assistant_hint'?: string;
}

type ExecuteResponseStatusEnum = 'success' | 'error' | 'empty' | 'preview'


