/*
Zapier AI Actions API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * This extends from ExecuteRequestBase to add the preview_only option.  (1) Providers who allow side effects or (2) actions that do not have a side effect should use this class.
 * @export
 * @interface ExecuteRequest
 */
export interface ExecuteRequest {
    /**
     * Plain english instructions. Provide as much detail as possible, even if other fields are present.
     * @type {string}
     * @memberof ExecuteRequest
     */
    'instructions': string;
    /**
     * If true, we will not execute the action, but will return the params of the preview.
     * @type {boolean}
     * @memberof ExecuteRequest
     */
    'preview_only'?: boolean;
}

