/*
Zapier AI Actions API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExposedActionSchema } from './exposed-action-schema';

/**
 * 
 * @export
 * @interface ExposedActionResponseSchema
 */
export interface ExposedActionResponseSchema {
    /**
     * 
     * @type {Array<ExposedActionSchema>}
     * @memberof ExposedActionResponseSchema
     */
    'results': Array<ExposedActionSchema>;
    /**
     * URL to configure and expose more actions.
     * @type {string}
     * @memberof ExposedActionResponseSchema
     */
    'configuration_link': string;
}

