/*
Zapier AI Actions API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExposedActionSchema
 */
export interface ExposedActionSchema {
    /**
     * Description of the action.
     * @type {string}
     * @memberof ExposedActionSchema
     */
    'description': string;
    /**
     * The unique ID of the exposed action.
     * @type {string}
     * @memberof ExposedActionSchema
     */
    'id': string;
    /**
     * The operation ID of the exposed action.
     * @type {string}
     * @memberof ExposedActionSchema
     */
    'operation_id': string;
    /**
     * Available hint fields for the action.
     * @type {object}
     * @memberof ExposedActionSchema
     */
    'params': object;
}

